#!/usr/bin/env bash
K8S_VER="" # <empty for latest> or given version
MIRROR="aliyun"
NODES=2
DOMAIN="mycloud.local"

function cluster_cmd(){
    COMMAND=$1 # start/stop/restart/delete
    for INSTANCE in $(multipass list|grep k8s-|awk '{print $1}');do
        multipass $COMMAND $INSTANCE &
    done
    wait
}

function setup_control_plane(){
    multipass launch --name k8s-control-plane --cpus 4 --mem 4G --disk 40G
    if [ $? -eq 0 ];then
        multipass mount $(pwd)/scripts/ k8s-control-plane:/opt/multipass-host/scripts
        multipass mount $(pwd)/share/ k8s-control-plane:/opt/multipass-host/share
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/init.sh $MIRROR"
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/nfs/server.sh"
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/dns/server.sh $DOMAIN"
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/openldap/server.sh $DOMAIN"
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/k8s/install.sh $K8S_VER"
        multipass exec k8s-control-plane -- sh -c "/opt/multipass-host/scripts/k8s/setup-control-plane.sh"
    fi
}

function setup_node(){
    NODE_INDEX=$1
    MASTER_IP=$(multipass list|grep k8s-control-plane|awk '{print $3}')
    multipass launch --name k8s-node-$NODE_INDEX --cpus 4 --mem 4G --disk 10G
    if [ $? -eq 0 ];then
        multipass mount $(pwd)/scripts k8s-node-$NODE_INDEX:/opt/multipass-host/scripts
        multipass mount $(pwd)/share k8s-node-$NODE_INDEX:/opt/multipass-host/share
        multipass exec k8s-node-$NODE_INDEX -- sh -c "/opt/multipass-host/scripts/init.sh $MIRROR"
        multipass exec k8s-node-$NODE_INDEX -- sh -c "/opt/multipass-host/scripts/nfs/client.sh $MASTER_IP"
        multipass exec k8s-node-$NODE_INDEX -- sh -c "/opt/multipass-host/scripts/dns/client.sh $MASTER_IP"
        multipass exec k8s-node-$NODE_INDEX -- sh -c "/opt/multipass-host/scripts/k8s/install.sh $K8S_VER"
        multipass exec k8s-node-$NODE_INDEX -- sh -c "/opt/multipass-host/scripts/k8s/setup-worker-node.sh"
    fi
}

function create_cluster(){
    setup_control_plane
    for INDEX in $(seq 1 $NODES) ;do
        setup_node $INDEX &
    done
    wait
}

function check_work_nodes_ready(){
    NOT_READY_NODES=$(multipass exec k8s-control-plane -- kubectl get nodes|grep "NotReady"|wc -l)
    if [ "$NOT_READY_NODES" -gt 0 ];then
        echo "These node(s) are not ready:"
        multipass exec k8s-control-plane -- kubectl get nodes|grep "NotReady"
    else
        echo "All nodes are ready."
    fi
}

function check_all_pods_running(){
    NOT_RUNNING_PODS=$(multipass exec k8s-control-plane -- kubectl get pod -A|grep -v "Running"|grep -v "NAMESPACE"|wc -l)
    if [ "$NOT_RUNNING_PODS" -gt 0 ];then
        echo "These pod(s) are not ready:"
        multipass exec k8s-control-plane -- kubectl get pod -A|grep -v "Running"
    else
        echo "All pods are running."
    fi

}

function check_all_nodes_ready(){
    CONTROL_PLANE_STATUS=$(multipass list|grep k8s-control-plane|awk '{print $2}')
    if [ "$CONTROL_PLANE_STATUS" == "Running" ];then
        check_work_nodes_ready
        check_all_pods_running
        exit 0
    else
        echo  "ERROR: k8s-control-plane instance is not running."
        exit 1
    fi
}


COMMAND=$1
SUB_COMMAND=$2

case $COMMAND in
"create")
    create_cluster
    ;;
"destroy")
    if [ -n "$SUB_COMMAND" ];then
        multipass delete -p $SUB_COMMAND
    else
        cluster_cmd stop
        cluster_cmd delete
        multipass purge
    fi
    ;;
"start")
    cluster_cmd start
    ;;
"stop")
    cluster_cmd stop
    ;;
"restart")
    cluster_cmd restart
    ;;
"check")
    check_all_nodes_ready
    ;;
"status")
    multipass list|grep k8s
    ;;
"login")
    multipass shell k8s-control-plane
    ;;
*)
    echo "usage: ./k8sctl [create|start|stop|restart|destroy|check|status|login]"
esac


